(() => {
'use strict';
const $=s=>document.querySelector(s);let config=structuredClone(window.STUDIO_CONTENT);const files=new Map(),urls=new Map();let selected='hero';const status=msg=>$('#status').textContent=msg;
function slots(){return [{id:'hero',title:'히어로 영상'},...config.works.map(w=>({id:w.id,title:w.title}))];}
function record(){return selected==='hero'?config.hero:config.works.find(w=>w.id===selected);}
function refreshSlots(){const select=$('#slot');select.replaceChildren();for(const s of slots()){const o=document.createElement('option');o.value=s.id;o.textContent=s.title;select.append(o);}select.value=selected;}
function fill(){const r=record();$('#title').value=r.title;$('#video-url').value=r.video||'';$('#poster-url').value=r.poster||'';$('#description').value=r.description||'';$('#concept').checked=!!r.concept;$('#work-fields').hidden=selected==='hero';$('#video-file').value='';$('#poster-file').value='';$('#video-name').textContent='';$('#poster-name').textContent='';}
function validUrl(s){if(!s)return true;if(s.startsWith('assets/')&&!s.includes('..')&&!/[<>"\\]/.test(s))return true;try{const u=new URL(s);return u.protocol==='https:'||u.protocol==='http:';}catch{return false;}}
function localFile(type,file){if(!file)return null;const accept=type==='video'?/^video\/(mp4|webm)$/:/^image\/(jpeg|png|webp|gif)$/;if(!accept.test(file.type))throw Error(type==='video'?'MP4 또는 WebM 파일을 선택해주세요.':'JPG, PNG, WebP 또는 GIF 파일을 선택해주세요.');if(file.size>100*1024*1024)throw Error('파일은 개당 100MB 이하로 선택해주세요.');const ext=file.name.split('.').pop().replace(/[^a-z0-9]/gi,'').toLowerCase();const safeId=selected.replace(/[^a-z0-9_-]/gi,'');const path=`assets/${safeId}-${type}-${Date.now()}.${ext}`;files.set(path,file);urls.set(path,URL.createObjectURL(file));return path;}
function apply(show=true){
 try {const r=record();const video=$('#video-url').value.trim(),poster=$('#poster-url').value.trim();if(!validUrl(video)||!validUrl(poster))throw Error('올바른 https 주소 또는 assets/ 파일 경로를 입력해주세요.');if(selected==='hero'&&/youtu\.?be|vimeo\.com/i.test(video))throw Error('히어로 배경에는 MP4·WebM 파일을 사용해주세요.');r.title=$('#title').value.trim()||r.title;r.video=localFile('video',$('#video-file').files[0])||video;r.poster=localFile('poster',$('#poster-file').files[0])||poster;if(selected!=='hero'){r.description=$('#description').value;r.concept=$('#concept').checked;}fill();refreshSlots();sendPreview();if(show)status('미리보기에 적용했습니다. ZIP을 다운로드하면 변경 내용을 저장할 수 있습니다.');return true;}catch(e){status(e.message);return false;}}
function sendPreview(){const p=structuredClone(config);for(const r of [p.hero,...p.works]){if(urls.has(r.video))r.video=urls.get(r.video);if(urls.has(r.poster))r.poster=urls.get(r.poster);}$('#preview').contentWindow.postMessage({type:'mplanit-preview',content:p},location.origin);}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function zip(entries){const parts=[],central=[];let offset=0,centralSize=0;const enc=new TextEncoder();for(const [name,data]of entries){const filename=enc.encode(name),crc=crc32(data),head=new Uint8Array(30+filename.length),dv=new DataView(head.buffer);dv.setUint32(0,0x04034b50,true);dv.setUint16(4,20,true);dv.setUint16(6,0x0800,true);dv.setUint32(14,crc,true);dv.setUint32(18,data.length,true);dv.setUint32(22,data.length,true);dv.setUint16(26,filename.length,true);head.set(filename,30);parts.push(head,data);const ch=new Uint8Array(46+filename.length),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x0800,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,filename.length,true);cv.setUint32(42,offset,true);ch.set(filename,46);central.push(ch);centralSize+=ch.length;offset+=head.length+data.length;}const end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'});}
async function exportSite(){if(!apply(false))return;const button=$('#export-site');button.disabled=true;status('영상과 사이트 파일을 ZIP으로 묶는 중입니다…');try{const enc=new TextEncoder(),entries=[],paths=new Set(['index.html','style.css','app.js','edit.html','editor.css','editor.js','VIDEO_GUIDE.md','assets/mplanit-logo.png','assets/hero-poster.jpg','assets/hero.mp4','assets/blue.png','assets/automotive.png','assets/beauty.png']);for(const r of [config.hero,...config.works])for(const p of [r.video,r.poster])if(p?.startsWith('assets/'))paths.add(p);for(const path of paths){const data=files.has(path)?new Uint8Array(await files.get(path).arrayBuffer()):await fetch(path).then(r=>{if(!r.ok)throw Error(path+' 파일을 읽지 못했습니다.');return r.arrayBuffer();}).then(b=>new Uint8Array(b));entries.push([path,data]);}const json=JSON.stringify(config,null,2);entries.push(['content.js',enc.encode('window.STUDIO_CONTENT = '+json+';\n')],['content.json',enc.encode(json)]);download(zip(entries),'MPLANIT_Motion_Studio.zip');status('ZIP 다운로드를 시작했습니다. 압축을 풀어 index.html을 열거나, 폴더 전체를 사이트에 배포하세요.');}catch(e){status('내보내기 실패: '+e.message+' 설정 파일은 별도로 다운로드할 수 있습니다.');}finally{button.disabled=false;}}
$('#slot').addEventListener('change',()=>{selected=$('#slot').value;fill();});$('#apply').addEventListener('click',()=>apply());$('#export-site').addEventListener('click',exportSite);$('#export-config').addEventListener('click',()=>{if(apply(false)){download(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}),'content.json');status('설정을 다운로드했습니다. 업로드한 영상 파일까지 포함하려면 사이트 ZIP을 다운로드해주세요.');}});
$('#video-file').addEventListener('change',()=>$('#video-name').textContent=$('#video-file').files[0]?.name||'');$('#poster-file').addEventListener('change',()=>$('#poster-name').textContent=$('#poster-file').files[0]?.name||'');
$('#import-config').addEventListener('change',async()=>{try{const f=$('#import-config').files[0];if(!f)return;const c=JSON.parse(await f.text());if(!c.hero||!c.brand||!c.contact||!Array.isArray(c.works)||c.works.length>100)throw Error('올바른 설정 파일이 아닙니다.');const ids=new Set();for(const r of [c.hero,...c.works]){if(typeof r.id!=='string'||!r.id||ids.has(r.id)||!validUrl(r.video)||!validUrl(r.poster))throw Error('설정의 영역 ID 또는 미디어 주소를 확인해주세요.');ids.add(r.id);}config=c;selected='hero';refreshSlots();fill();sendPreview();status('설정을 불러왔습니다. 파일 경로로 연결된 영상은 기존 사이트 파일과 함께 보관해주세요.');}catch(e){status(e.message);}});
$('#preview').addEventListener('load',sendPreview);for(const mode of ['desktop','mobile'])$('#'+mode).addEventListener('click',()=>{$('#preview').classList.toggle('mobile',mode==='mobile');for(const name of ['desktop','mobile']){$('#'+name).classList.toggle('selected',name===mode);$('#'+name).setAttribute('aria-pressed',String(name===mode));}});
refreshSlots();fill();
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_media_configuration',title:'영상 구성 확인',description:'현재 편집 화면의 미디어 구성을 읽습니다. 공개 사이트에 저장된 변경을 의미하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>structuredClone(config)});
 register({name:'stage_media_updates',title:'영상 교체 미리보기',description:'영상 URL과 포스터 URL을 편집 화면 및 미리보기에 적용합니다. 공개 사이트를 변경하거나 파일을 저장하지 않습니다.',inputSchema:{type:'object',properties:{updates:{type:'array',minItems:1,maxItems:20,items:{type:'object',properties:{id:{type:'string'},video:{type:'string'},poster:{type:'string'},title:{type:'string'}},required:['id'],additionalProperties:false}}},required:['updates'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{
  if(!input||!Array.isArray(input.updates)||input.updates.length<1||input.updates.length>20)throw Error('updates 배열은 1~20개여야 합니다.');
  const next=structuredClone(config);
  for(const update of input.updates){if(!update||typeof update.id!=='string'||Object.keys(update).some(k=>!['id','video','poster','title'].includes(k)))throw Error('지원되지 않는 필드입니다.');const target=update.id==='hero'?next.hero:next.works.find(w=>w.id===update.id);if(!target)throw Error('알 수 없는 영역입니다.');for(const key of ['video','poster'])if(key in update){if(typeof update[key]!=='string'||!validUrl(update[key]))throw Error('잘못된 미디어 URL입니다.');if(update.id==='hero'&&key==='video'&&/youtu\.?be|vimeo\.com/i.test(update[key]))throw Error('히어로는 MP4 또는 WebM을 사용합니다.');target[key]=update[key];}if('title'in update){if(typeof update.title!=='string'||!update.title.trim()||update.title.length>150)throw Error('제목을 확인해주세요.');target.title=update.title;}}
  config=next;refreshSlots();fill();sendPreview();status('미디어 교체를 미리보기에 적용했습니다. ZIP으로 내보내야 저장됩니다.');return{status:'staged',updated:input.updates.map(u=>u.id),published:false};
 }});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
})();
